name: RELEASE
on:
  push:
env:
  NODE_VERSION: 18.15.0
  PNPM_VERSION: 7.27.1
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  lint-and-format:
    name: Create Release Pull Request
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-environment
        with:
          node-version: '${{ env.NODE_VERSION }}'
          pnpm-version: '${{ env.PNPM_VERSION }}'
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}